name: CI

on:
  push:
    branches:
      - main
      - service
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 3306:3306
          - 9000:8080

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up Docker Compose
      run: sudo apt-get update && sudo apt-get install docker-compose -y

    - name: Build and run containers
      run: docker-compose up -d

    - name: Wait for MySQL to be ready
      run: |
        until docker exec -i $(docker ps -q -f name=db) mysqladmin ping --silent; do
          echo 'Waiting for MySQL...'
          sleep 5
        done

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test

    - name: Shut down Docker Compose
      run: docker-compose down
